language: python
os:
  - linux
python:
  - "3.5"
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
<<<<<<< HEAD
  - pylint imap_storage
=======
>>>>>>> branch 'master' of git@github.com:snake-soft/imap-storage.git
  - python -m unittest
